name: Typescript

on: 
  push:
  pull_request:

jobs:
  tsc:
    name: Typescript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15
      
      - name: Install dependencies
        run: yarn install
        
      - name: Compile Typescript
        uses: icrawl/action-tsc@v1
